tru-proxy:
  endpoint-uri: https://exercise.trunarrative.cloud/TruProxyAPI/rest/Companies/v1
  api-key: 
spring:
  sql:
    init:
      mode: always
  datasource:
    username: truproxy
    password: truproxy
    url: jdbc:postgresql://localhost:5432/truproxy
    driverClassName: org.postgresql.Driver